name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun run all

  test:
    needs: build

    if: ${{ github.repository_owner == 'dennisameling' && github.actor != 'dependabot[bot]' }}

    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v7
      - name: test with testFolder
        uses: ./
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: dummydata/testFolder/
          server_dir: ${{ matrix.os }}/
      - name: test with testFolderRecursive
        uses: ./
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: dummydata/testFolderRecursive/
          server_dir: ${{ matrix.os }}/
